[package]
name = "one-last-image-rslib"
edition = "2024"
description = "Extra library for koishi-plugin-one-last-image written in Rust"
license = "MPL-2.0"
homepage = "https://github.com/Hoshino-Yumetsuki/koishi-plugin-one-last-image"
repository = "https://github.com/Hoshino-Yumetsuki/koishi-plugin-one-last-image"

[lib]
crate-type = ["cdylib"]

[dependencies]
image = "^0.25.8"
js-sys = "^0.3.81"
wasm-bindgen = "^0.2.104"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
base64 = "^0.22.1"
imageproc = "^0.25.0"
ndarray = "^0.16.1"

